Welcome to The Weird West!

You woke up on the side of the road just outside of town with no memory of where you are, how you got there... or even who you are.

Unsure of what you should be doing, you walked toward the town. Along the way, you encountered an old man who said he recognized you from the other side. He told you to find the doorway home. He said it was in the town.

You strolled down the main street and saw no activity along the way. This is a strange little town, I'll tell you what. 

Does anyone live here? Is it a ghost town? What kind of doorway are you looking for? Is that a horse... talking to itself?